// WEBCOM-LUBRICANTES - NUEVO-PEDIDO - SELECCION-TIPO-PEDIDO

import './01-CARGA_DE_TABLA_RESUMEN.cy';
import './02-RESUMEN_DE_UN_PRODUCTO.cy';
import './03-RESUMEN_VARIOS_PRODUCTOS.cy';
import './04-ELIMINAR_TODOS_LOS_PRODUCTOS.cy';
import './05-ELIMINAR_PRODUCTO.cy';
import './06-ELIMINAR_VARIOS_PRODUCTOS.cy';
import './07-EDITAR_PRODUCTO.cy';
