// WEBCOM-LUBRICANTES - NUEVO-PEDIDO - SELECCION-TIPO-PEDIDO

import './01-CARGA_DE_TABLA.cy';
import './02-LLENAR_TABLA_SIMPLE.cy';
import './03-LLENAR_TABLA_SIMPLE_CON_ERROR.cy';
import './04-LLENAR_TABLA_COMPLEJO.cy';
