// WEBCOM-VVDD-MISPEDIDOS

import './PRUEBA_01 - BUSQUEDA DE PEDIDO.cy';
import './PRUEBA_02 - ORDENAR TABLA FILTROS.cy';
import './PRUEBA_03 - DESCARGA LISTA DE RESULTADOS.cy';
import './PRUEBA_04 - DETALLE DE LA SOLICITUD.cy';
import './PRUEBA_05 - DESCARGA DETALLE DE LA SOLICITUD.cy';
import './PRUEBA_06 - INCIDENCIA DE PEDIDO.cy';
import './PRUEBA_07 - REPETIR PEDIDO COMPLETO.cy';
import './PRUEBA_08 - REPETIR SOLO UN PRODUCTO.cy';
import './PRUEBA_09 - DETALLE DEL PRODUCTO.cy';
