// WEBCOM-STARRESSA-DETALLEOPERACIONES

import './PRUEBA_01-FORMULARIO_RESULTADOS.cy';
import './PRUEBA_02-FILTROS_TABLA.cy';
import './PRUEBA_03-DESCARGA_DEL_EXCEL.cy';
import './PRUEBA_04-PAGINACIÓN_TABLA.cy';
