// WEBCOM-LUBRICANTES - NUEVO-PEDIDO - SLECCION-TIPO-PEDIDO

import './01-CARGA_DE_FORMULARIO.cy';
import './02-BUSQUEDA_SIN_FILTROS.cy';
import './03-BUSQUEDA_FILTRO_MARCA.cy';
import './04-BUSQUEDA_FILTRO_NOMBRE.cy';
import './05-BUSQUEDA_FILTRO_CATEGORIA.cy';
import './06-BUSQUEDA_FILTRO_TIPO.cy';
import './07-BUSQUEDA_FILTRO_SKU.cy';
import './08-BUSQUEDA_FILTRO_EAN.cy';
